export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_ALL_ARICLES = 'LOAD_ALL_ARICLES'
export const LOAD_ARTICLE_BY_ID = 'LOAD_ARTICLE_BY_ID'

export const LOAD_COMMENTS_FOR_ARTICLE = 'LOAD_COMMENTS_FOR_ARTICLE'
export const LOAD_COMMENTS_FOR_PAGE = 'LOAD_COMMENTS_FOR_PAGE'

export const LOGIN = 'LOGIN'

export const _START = '_START'
export const _SUCCESS = '_SUCCESS'
export const _FAIL = '_FAIL'